import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "packages/database/drizzle/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Generated by Next; triple-slash reference is its canonical shape.
  {
    files: ["apps/web/next-env.d.ts"],
    rules: { "@typescript-eslint/triple-slash-reference": "off" },
  },
);
